name: opencv
channels:
    - pytorch
    - conda-forge
    - anaconda
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - tensorboardX
  - meshzoo
  - path
  - scikit-image
  - lmdb
  - tqdm
  - opencv
  - lpips

